insert into categoria
(nombre                         , descripcion ) values
('Primera División de Argentina', 'Es el torneo de la primera categoría del fútbol masculino argentino, organizado desde 1893 por la Asociación del Fútbol Argentino'),
('Primera B Nacional'           , 'Cuyo nombre de fantasía es Primera Nacional —también conocida como Nacional B, B Nacional o Torneo Nacional B— es el campeonato de fútbol de segunda división de Argentina.'),
('Primera B'                    , 'También llamada Primera B Metropolitana, o informalmente B Metropolitana o B Metro) es la tercera categoría del fútbol argentino para los clubes directamente afiliados a la AFA.');

insert into club
(nombre                       , categoria_id,  descripcion                                                                                     , imagen_url) values
('Club Atlético Boca Juniors' , 1 , 'Es una entidad deportiva argentina con sede en el barrio de La Boca, Buenos Aires. Fue fundado en dicho barrio el 3 de abril de 1905 por seis vecinos adolescentes hijos de italianos.' ,'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Boca_Juniors_logo18.svg/1200px-Boca_Juniors_logo18.svg.png'),
('Club Atlético River Plate'  , 1 , 'Es una entidad polideportiva con sede en Buenos Aires, Argentina. Fue fundado el 25 de mayo de 1901 en el barrio de La Boca'                                                            ,'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/CA_river_plate_logo.svg/1200px-CA_river_plate_logo.svg.png'),
('Club Atlético Independiente', 1 , 'Conocido popularmente como Independiente o por su sigla CAI, es una entidad deportiva de Argentina de la ciudad de Avellaneda'                                                          ,'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Escudo_del_Club_Atl%C3%A9tico_Independiente_de_Avellaneda.svg/1200px-Escudo_del_Club_Atl%C3%A9tico_Independiente_de_Avellaneda.svg.png'),
('Racing Club'                , 1 , 'Conocido como Racing Club de Avellaneda o simplemente Racing, es una entidad deportiva oriunda de Argentina, fundada el 25 de marzo de 1903 en la Ciudad de Avellaneda'                 ,'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Escudo_de_Racing_Club_%282014%29.svg/1200px-Escudo_de_Racing_Club_%282014%29.svg.png'),
('Club Atlético Atlanta'      , 2 , 'Es una institución social, cultural y deportiva argentina, radicada en el barrio de Villa Crespo'                                                                                       ,'https://upload.wikimedia.org/wikipedia/commons/0/0b/C.a._atlanta.png'),
('Club Atlético Belgrano'     , 2 , 'Es una institución deportiva de la ciudad de Córdoba en Argentina. Fue fundado oficialmente un lunes 19 de marzo de 1905'                                                               ,'https://upload.wikimedia.org/wikipedia/commons/8/85/Escudo_Oficial_del_Club_Atl%C3%A9tico_Belgrano.png'),
('Club Atlético San Miguel'   , 3 , 'Es un club cuya actividad de mayor referencia es el fútbol. Fue fundado el 7 de agosto de 1922. Tiene su sede social en el Partido de San Miguel.'                                      ,'https://upload.wikimedia.org/wikipedia/commons/4/45/Club_Atletico_SAN_MIGUEL.png');